config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'reports/index'
  root to: "reports#index"
  resources :users, only: [:edit, :update]
  resources :reports, only: [:index, :new, :create]
  namespace :admin do
    resources :reports, only: [:index, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/report.rb
class Report < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :reports

  with_options presence: true do
    validates :employee_number
    validates :department
    validates :position 
    with_options format: { with: /\A[ぁ-んァ-ヶ一-龥々ー]+\z/ } do
      validates :last_name
      validates :first_name
    end
  end
end

app/controllers/admin/reports_controller.rb
class Admin::ReportsController < 
  before_action :if_not_admin

  def index
    @reports = Report.all
    @reports = Report.find(params[:id])
  end
  

  require "date"

  def new
    @reports = Report.new
  end

  def create
    @reports = Report.new(reports_params)
    case params[:commit]
      when "出勤" ; @reports.start_of_work = Time.now
      when "開始" ; @reports.breakstart = Time.now
      when "終了" ; @reports.breakend = Time.now
      when "退勤" ; @reports.end_of_work = Time.now
      when "end_of_work" ; @reports.business_content
    end
    if @reports.save
      redirect_to root_path
    else
      render :index
    end  
  end

  respond_to do |format|
    format.csv do
      send_data render_to_string, filename: "在宅勤務管理.csv", type: :csv
    end
  end
  
  private
  def if_not_admin
    redirect_to root_path unless current_user.admin?
  end

  def set_report
    @reports = Report.find(params[:id])
  end

  def reports_params
    params.permit(:start_of_work, :breakstart, :breakend, :end_of_work, :business_content).merge(user_id: current_user.id)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :basic_auth
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  private

  def basic_auth
    authenticate_or_request_with_http_basic do |username, password|
      username == ENV["BASIC_AUTH_USER"] && password == ENV["BASIC_AUTH_PASSWORD"]
    end
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:employee_number, :last_name, :first_name, :department, :position])
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @reports = Report.all
  end

  require "date"

  def new
    @reports = Report.new
  end

  def create
    @reports = Report.new(reports_params)
    case params[:commit]
      when "出勤" ; @reports.start_of_work = Time.now
      when "開始" ; @reports.breakstart = Time.now
      when "終了" ; @reports.breakend = Time.now
      when "退勤" ; @reports.end_of_work = Time.now
      when "end_of_work" ; @reports.business_content
    end
    if @reports.save
      redirect_to root_path
    else
      render :index
    end  
  end

  respond_to do |format|
    format.csv do
      send_data render_to_string, filename: "在宅勤務管理.csv", type: :csv
    end
  end

  private
  def reports_params
    params.permit(:start_of_work, :breakstart, :breakend, :end_of_work, :business_content).merge(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def edit    
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:employee_number, :last_name, :first_name, :email, :department, :position)
  end
end

app/helpers/admin/reports_helper.rb
module Admin::ReportsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HomeBusinessApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" type="text/css" href="http://yui.yahooapis.com/3.18.1/build/cssreset/cssreset-min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reports/_main_bar.html.erb
<div class="main-header">
    <div class="left-header">
    <div class="header-title">
      <%= "#{current_user.department}"%>
    </div>
  </div>
  <div class="right-header">
    <div class="header-button">
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn' %>
    </div>
  </div>
</div>

<div class="reports">
  <%= render partial: 'report', collection: @reports %>
</div>

<div class="footer">
  <% if user_signed_in? %>
    <% if current_user == @user || current_user.admin? %>
        <div class="footer-button">
        <%= link_to "CSV", root_path(format: :csv), class: "btn" %>
        </div>
    <% end %>
  <% end %>
</div>

app/views/reports/_report.html.erb
<div class="report">
  <div class="upper-report">
    <div class="report-user">
      <!-- 報告したユーザー名情報を出力する -->
      <%= report.user.last_name %>
      <%= report.user.first_name %>
    </div>
    <div class="report-date">
      <!-- 報告した時刻を出力する -->
     <p><%= "勤務開始：" %>
        <% if report.start_of_work != nil %>
          <%= l report.start_of_work, format: :short %>
        <% end %> 
      </p>
     <p><%= "休憩開始：" %>
        <% if report.breakstart != nil %>
          <%= l report.breakstart, format: :short %>
        <% end %> 
      </p>
     <p><%= "休憩完了：" %>
        <% if report.breakend != nil %>
          <%= l report.breakend, format: :short %>
        <% end %> 
      </p>
     <p><%= "勤務終了："%>
        <% if report.end_of_work != nil %>
          <%= l report.end_of_work, format: :short %>
        <% end %> 
      </p>
    </div>
  </div>
  <div class="lower-report">
    <div class="report-content">
      <!-- 業務内容を表示する -->
      <p><%= "実施報告：" "#{report.business_content}" %></p>
    </div>
  </div>
</div>

app/views/reports/_side_bar.html.erb
<div class="side-bar-header" >
  <div class="header-name">
    <%= link_to current_user.employee_number, edit_user_path(current_user) %>
    </a>
  </div>
  <div class="menu-list">
    <%= link_to "打刻・報告", new_report_path %>
  </div>
</div>

<div class="menus">
  <div class="menu">
    <div class="menu-name">
      <a href="#">勤務状況一覧</a>
    </div>
  </div>
  <div class="menu">
    <div class="menu-name">
      <a href="#">チームMTG</a>
    </div>
  </div>
</div>

app/views/reports/index.html.erb
<div class="wrapper">
  <div class="side_bar">
    <%= render "side_bar"%>
  </div>
  <div class= "main_bar">
    <%= render "main_bar"%>
  </div>
</div>

app/views/reports/new.html.erb
<div class='report-form'>
  <h1>打刻・報告</h1>
  <%=form_with model: @reports, local: true do |f|%>
    <div class='report-form__field'>
      <div class='report-form__field--left'>
        <%= f.label :勤務開始, class: 'report-form__label'%>
      </div>
      <div class='report-form__field--right'>
        <%= f.submit "出勤", id: "start_of_work", class: 'report-form__action-btn' %>
      </div>
    </div>
    <div class='report-form__field'>
    </div>
    <div class='report-form__field--left'>
      <%= f.label :休憩時間, id: "breakstart", class: 'report-form__label'%>
    </div>
    <div class='report-form__field--right'>
        <%= f.submit "開始", class: 'report-form__action-btn' %>
    </div>
    <div class='report-form__field'>
    </div>
    <div class='report-form__field--right'>
        <%= f.submit "終了", id: "breakend", class: 'report-form__action-btn' %>
    </div>
    <div class='report-form__field'>
    </div>
    <div class='report-form__field'>
    </div>
    <div class='report-form__field--left'>
      <%= f.label :勤務終了, class: 'report-form__label'%>
    </div>
    <div class='report-form__field--right'>
        <%= f.submit "退勤", id: "end_of_work", class: 'report-form__action-btn' %>
    </div>
    <div class='report-form__field'>
    </div>
    <div class='report-form__field'>
    <div class='report-form__field--left'>
      <%= f.label :実施報告, class: 'report-form__label'%>
    </div>
    <div class='report-form__field--right'>
      <%= f.text_area :business_content, id: "end_of_work", class: 'report-form_name report-form__input', placeholder: 'お疲れさまでした', rows: "5" %>
    </div>
    </div>
    <div class='report-form__field'>
      <div class='report-form__field--left'></div>
      <div class='report-form__field--right'>
        <%= f.submit '報告する',  id: "end_of_work", class: 'report-form__action-btn'%>
        <%= link_to "一覧ページに戻る", :back, class: 'report-form__action-btn'%>
      </div>
    </div>
  <% end %>
</div>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>アカウントの編集</h2>
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'%>
      <%= link_to "一覧ページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :employee_number, "社員番号"%>
          </div>
          <div class='field-input'>
            <%= f.text_field :employee_number%>
          </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :last_name, "氏"%>
            <%= f.label :first_name, "名"%>
          </div>
          <div class='field-input-name'>
            <%= f.text_field :last_name, autofocus: true%>
            <%= f.text_field :first_name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email, "Eメール"%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='field-down'>
          <div class='field-label'>
            <%= f.label :department, "部署名"%>
          <div class='field-input'>
            <%= f.text_field :department, autocomplete: "off"%>
          </div>
          <div class='field-label'>
            <%= f.label :position, "役職名"%>
          <div class='field-input'>
            <%= f.text_field :position, autocomplete: "off"%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "更新する", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>